---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/external-secrets
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/cert-manager
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: cert-manager
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    see: https://cert-manager.io/docs/installation/kubernetes/
  syncOptions:
    - Validate=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/external-dns
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-nfs-server-provisioner
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/nfs-server-provisioner
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-elasticsearch
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/elasticsearch
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-kibana
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/kibana
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-fluentd
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: {{ .Values.infra_repo_ssh_url }}
    path: .cd/bases/apps/fluentd
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
