---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argo_project }}-common-namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: {{ .Values.argo_project }}
  source:
    repoURL: https://github.com/hagzag/experiments.git
    path: argo/common-ns
    targetRevision: {{ .Values.infra_repo_ref }}
  destination:
    server: {{ .Values.destination_cluster }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true