---
apiVersion: v1
kind: Namespace
metadata:
  name: data
	annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
	annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
	annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
	annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
	annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io